### ISSUE TITLE
Server connection lost

### ISSUE THREAD

**Issue by Sardaukai** [StalkR/Space-Engineers-Asteroid-Ores#10]
Hey, 
since the last update we got a problem.

If one fly at space everyone at the server gets connection problems.

Voxels gets generated fine but it simply takes to much server time.
Servers idle time is about 6ms/f

I think there is a bad check which takes to much time and causes a lot of trouble.
Maybe we can tune that a bit and rollback to old till fixed?

**Comment by StalkR** [comment]
Hey, thanks for the report. I'm not sure what's the issue exactly, but I have some ideas. I've reworked the code and pushed a new mod update, does it fix the issues you've observed?

It goes without saying, make sure you have the latest plugin release, currently [0.5.1](https://torchapi.com/plugins/view/23f5bd00-e6bd-430c-960e-b66d34c05060), and mods up to date. It's important because previously plugin was communicating with the mod but not anymore, which is also a reason why a rollback isn't easily possible. It will be better going forward with plugin/mod now well separated.

**Comment by Sardaukai** [comment]
Great, we will check it.

The mod is added to our server modlist and updated.

**Comment by Sardaukai** [comment]
Issue is fixed, thanks a lot !!

Do you also fixed the spectator bug?

**Comment by StalkR** [comment]
great! yes spectator bug (#3) is also fixed
