### ISSUE TITLE
config reset 

### ISSUE THREAD

**Issue by daddydante88** [StalkR/Space-Engineers-Asteroid-Ores#7]
Issue with configuration file resetting on its own after mod is setup and working fine.

**Comment by StalkR** [comment]
hey, sorry I don't know what's your issue as it's working fine for everyone.

Note Torch itself handles configuration parsing, loading and saving.

The only case I'm aware that the mod will reset the configuration is if the configuration is invalid and fails to load. As far as I know, that would be the same for all other plugins using Torch config system.

Invalid configuration can happen with invalid modifications, or if file is corrupted. In particular, be careful changing configuration files while the server is running, as you might be conflicting with Torch.

If you have a valid config that triggers a reset, feel free to share and I can take a look, but otherwise I'm afraid I can't do anything.
